-- AlterTable
ALTER TABLE `user` ADD COLUMN `ImageUrl` VARCHAR(191),
    ADD COLUMN `IsActive` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `Password` VARCHAR(191),
    ADD COLUMN `ThumbnailUrl` VARCHAR(191);
